export enum ErrorCode {
    MemberNotFound = "MEMBER_NOT_FOUND",
    RoleNotFound = "ROLE_NOT_FOUND",
    UserNotFound = "USER_NOT_FOUND",
    ProjectNotFound = "PROJECT_NOT_FOUND",
    PermissionDenied = "PERMISSION_DENIED",
    UserUnauthenticated = "USER_UNAUTHENTICATED",
    DatabaseError = "DATABASE_ERROR",
    InvalidKeyID = "INVALID_KEY_ID",
    KeyAlreadyExists = "KEY_ALREADY_EXISTS",
    AlreadyMember = "ALREADY_MEMBER",
    CannotDeleteSelf = "CAN_NOT_DELETE_SELF",
    LanguageNotValid = "LANGUAGE_NOT_VALID",
    TechnologyNotValid = "TECHNOLOGY_NOT_VALID",
}
