export enum Language {
    Arabic = "AR",
    Czech = "CS",
    Danish = "DA",
    German = "DE",
    Greek = "EL",
    EnglishAmerican = "EN-US",
    Spanish = "ES",
    Finnish = "FI",
    French = "FR",
    Hungarian = "HU",
    Indonesian = "ID",
    Italian = "IT",
    Japanese = "JA",
    Korean = "KO",
    Dutch = "NL",
    Polish = "PL",
    PortugueseBrazilian = "PT-BR",
    PortugueseEuropean = "PT-PT",
    Romanian = "RO",
    Russian = "RU",
    Swedish = "SV",
    Turkish = "TR",
    MandarinChineseSimplified = "ZH"
}
